spring:
  application:
    name: productivity-x-backend
  datasource:
    url: jdbc:postgresql://192.168.146.128:5432/focusdb
    username: focus
    password: focuspass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-on-validation-error: true
    clean-disabled: false

server:
  port: 8080
  ssl:
    enabled: false # Terminated at Ingress/LB usually, or set to true if testing local mTLS directly

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.productivityx: DEBUG

    org.springframework.security: INFO

productivityx:
  security:
    mtls-header: "X-Client-Cert-Hash" # For simulation or LB forwarding
